### PR TITLE
update yarn.lock

### PR DESCRIPTION
**Pull request by Strangehill**
...so that yarn install doesn't fail, an issue also existing at https://github.com/Vagr9K/gatsby-material-starter/issues/34

### CODE REVIEW

**Comment by Vagr9K** [comment]
Closing in favor of https://github.com/Vagr9K/gatsby-advanced-starter/commit/77a1e8f9893bbbacdfb4123b44d4d458f41cb46d since it updates dependencies and syncs both lockfiles.

**Comment by Strangehill** [comment]
I'm still having this issue, `yarn install` fails with fresh clone, and in `gatsby new`

**Comment by Vagr9K** [comment]
What's the exact error message?

Full log would be nice, since I can't reproduce the issue.

**Comment by Strangehill** [comment]
```
└─[$] gatsby new adv-start https://github.com/Vagr9K/gatsby-advanced-starter                                                                       [11:44:44]
info Creating new site from git: https://github.com/Vagr9K/gatsby-advanced-starter.git
Cloning into 'adv-start'...
remote: Counting objects: 1808, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 1808 (delta 6), reused 15 (delta 5), pack-reused 1788
Receiving objects: 100% (1808/1808), 3.06 MiB | 482.00 KiB/s, done.
Resolving deltas: 100% (1054/1054), done.
success Created starter directory layout
info Installing packages...
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
warning "gatsby-transformer-remark > graphql-type-json@0.1.4" has unmet peer dependency "graphql@>=0.4.0".
warning " > react-disqus-comments@1.1.1" has incorrect peer dependency "react@^15.0.1".
warning " > react-disqus-comments@1.1.1" has incorrect peer dependency "react-dom@^15.0.1".
warning " > stylelint-config-standard@18.0.0" has incorrect peer dependency "stylelint@^8.3.0".
warning "stylelint-config-standard > stylelint-config-recommended@2.0.1" has incorrect peer dependency "stylelint@^8.3.0".
[4/4] 📃  Building fresh packages...
[1/5] ⠠ fsevents
[-/5] ⠠ waiting...
[3/5] ⠠ pngquant-bin
[4/5] ⠠ cwebp-bin
error An unexpected error occurred: "/Users/cog/adv-start/node_modules/sharp: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/cog/adv-start/node_modules/sharp
Output:
module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/cog/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)




error Command failed: yarnpkg


  Error: Command failed: yarnpkg

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18

  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19

  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14

  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:693:18

  - async.js:133 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
```

**Comment by Vagr9K** [comment]
Seems like it's a sharp issue.

https://github.com/gatsbyjs/gatsby/issues/1754

Try [this workaround](https://github.com/gatsbyjs/gatsby/issues/1754#issuecomment-368000009) for now until the update actually hits the NPM.

Also, do you have GCC/clang setup on your system?

**Comment by Strangehill** [comment]
I do have gcc and clang set up.

`yarn upgrade` is a good fix though. I'm using yarn 1.5.1

**Comment by Vagr9K** [comment]
Hmm.

Can you post your new yarn.lock? I'd like to compare.

The one in the PR is no longer valid due to dependency upgrades.

**Comment by Strangehill** [comment]
https://github.com/Vagr9K/gatsby-advanced-starter/compare/master...Strangehill:upgrade-yarn-lock

**Pull request closed without merging**
