### PR TITLE
Fix date formating and sorting

### PR DESCRIPTION
**Pull request by Kageetai**
Several fixes:
- sorting of blog posts was broken
- proper date handling with [momentjs](https://github.com/moment/moment)
- configurable date formats from config
- display dates on index page
- use title from file name of no front matter
- properly handle posts in content root
- some minor eslint and prettier fixes and added `.eslintignore`
- pagination via [gatsby-paginate](https://github.com/pixelstew/gatsby-paginate)
- show post excerpt on post listing to show other fields of Remark
- display category in post template

PS.:
PR looks big due to added `package-lock.json`

### CODE REVIEW

**Comment by Vagr9K** [comment]
Thanks for the pull request! Really appreciated!

Is this still work in progress?

**Comment by Kageetai** [comment]
Well, this is the cumulation of me playing around with Gatsby and your starter for the last two or three days. So maybe I could find more, but for now I think this is a good start to generally improve the starter :)
I am not sure what codacy is complaining about though, because it's not actually showing any issues.

**Comment by Vagr9K** [comment]
Seems like it's stuck reviewing the code for some reason.

I'll find some time to review and merge your pull request (probably this evening).

Thanks!

**Comment by Kageetai** [comment]
I just noticed that the build version with `gatsby serve` doesn't really work. Maybe you have a idea

**Comment by Vagr9K** [comment]
Seems like it's the pagination breaking it.
No idea why though.

Gatsby just fails to generate those pages.

**Comment by Vagr9K** [comment]
Seems like it's the pagination breaking it.
No idea why though.

Gatsby just fails to generate those pages.

**Comment by ChrisSki** [comment]
Looking forward to these changes since I've been hitting some as well.

**Comment by Kageetai** [comment]
Hmm, I could maybe take out the pagination or make it optional for now. Let me see

**Comment by Kageetai** [comment]
Actually... (can't believe didn't test that before) it also happens with a clean build from a starter...

**Comment by Vagr9K** [comment]
The `master` you mean?

**Comment by Kageetai** [comment]
Yes, and even with the default starter I always get the same error. Guess something else is fundamentally wrong. I'll investigate more...

**Comment by Vagr9K** [comment]
Clean your package cache.
Master works.
I'll see which package actually breaks it when updated.

**Comment by Vagr9K** [comment]
Seems like the `gatsby` update breaks it.

**Comment by Kageetai** [comment]
Hmm, I tried `npm cache clean` but that didn't help and I am getting the same error with a totally clean newly generated project from this starter. It works fine a project from the default starter though.
Which gatsby update do you mean breaks it?

**Comment by Vagr9K** [comment]
Erm, just nuke your `node_modules`.
 I think the main gatsby package itself is breaking it, otherwise the plugins would output errors.

I am also using yarn. That shouldn't make any difference, but lately npm was less than reliable in regards to gatsby.

**Comment by Kageetai** [comment]
I tried that as well and even with yarn
Will try later today at another computer. Can you try if you can run my fork normally with `gatsby build && gatsby serve`?

**Comment by Vagr9K** [comment]
> Can you try if you can run my fork normally with gatsby build && gatsby serve

Nope.
The `master` works as long as I don't update any packages.
I don't think this is an issue specific to your fork. I haven't updated gatsby packages for a long time and now there are probably compatibility issues with the new version.

Lack of time is a bad thing :/

**Comment by Kageetai** [comment]
Hey, I finally had some more time and did some playing around with different versions for the packages and even tried to update all packages.
But in the end the error was about the `pathPrefix` like described in this issue: https://github.com/gatsbyjs/gatsby/issues/2740
I was just doing a normal build and serve without any prefix, but then your `gatsby-config.js` still sets the `pathPrefix` and that breaks links. I adjusted the `pathPrefix` in the `SiteConfig.js` and added a little comment for that for now, but it also seems they will be a PR to fix the issue I linked.

**Comment by Vagr9K** [comment]
Great work so far!

Do you mind breaking this PR down to smaller parts?
I feel like it's time to start reviewing and merging those PRs.

**Comment by Kageetai** [comment]
Hey, sorry for the delay, but pre-christmas-business... :)

Why do you want to split this PR into several smaller ones? To be honest, I don't see the value in that extra effort. This PR looks bigger than it is, mostly because of the added `package-lock.json` and I think it's easier/faster to merge it in one PR.
I'll check codeclimate and codacy now though

**Comment by Vagr9K** [comment]
Hey there!

Sorry for the delay. December was busy.

I wanted to break down this PR because of maintainability reasons. Keeping Git history clean and consistent proved itself to be worth the time investment, especially considering the issues with gatsby-paginate.

Apparently gatsby-paginate is [licensed as GPL](https://github.com/pixelstew/gatsby-paginate/issues/11), which creates a legal mess if you want to use the starter in commercial environments.

A native pagination module will probably be implemented in the future.

I've also bumped the gatsby version in master since some people requested that. It also fixes the `pathPrefix` issue without any hacks.


I really value your contribution and don't want to request you to do the double amount of work, and I think I have the time to separate the date sorting related part of this code and merge it in a separate PR while giving you the proper credit.

That being said if you prefer to do that yourself, just give me a heads up.

**Comment by Kageetai** [comment]
Hey,
yes the date sorting was my main point in this PR :)
The rest was mostly minor (but still sometimes crucial IMO) tweaks, like displaying excerpt and category on posts as an example and actually running prettier on everything.
So I guess you're right saying this PR got a bit too big and would be better separated out. I am not sure I will find the time for this this month, so let me know if you find the time first and can integrate some of the changes.
In the meantime I've started on (reworking) my personal blog using your starter and my changes :)

**Comment by JohnBra** [comment]
In case anybody is looking for a quick fix for the date formatting and sorting issue until this PR is resolved, you can format the dates in the frontmatter section of the .md files like you would in SQL ("YYYY-MM-DD") instead of the current formatting with slashes - like so:



If you wanted some date formatting in your blog posts, you can then use the GraphQL formatting, as in:



hope that helps.

**Comment by Vagr9K** [comment]
It took me a while to find some time for this, but https://github.com/Vagr9K/gatsby-advanced-starter/pull/33 finally fixes date related issues, eslint warning, etc.

I'd like to thank you for originally proposing this and putting things on motion!

**Comment by Kageetai** [comment]
@Vagr9K Nice to see. I nearly forgot about this PR myself :)
I quickly looked at your changes in the other PR and looks good as well. Happy to have been of some help

**Pull request closed without merging**
